include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_lambdas
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
