// Mocks generated by Mockito 5.x from annotations
// in hybrid_location/test/hybrid_location_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:hybrid_location/src/models/hybrid_location_result.dart'
    as _i3;
import 'package:hybrid_location/src/models/location_source.dart' as _i4;
import 'package:hybrid_location/src/providers/base_location_provider.dart'
    as _i1;
import 'package:mockito/mockito.dart' as _i5;

/// A class which mocks [BaseLocationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLocationProvider extends _i5.Mock
    implements _i1.BaseLocationProvider {
  MockBaseLocationProvider() {
    _i5.throwOnMissingStub(this);
  }

  @override
  _i4.LocationSource get source =>
      (super.noSuchMethod(
            Invocation.getter(#source),
            returnValue: _i4.LocationSource.unknown,
          )
          as _i4.LocationSource);

  @override
  _i2.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<_i3.HybridLocationResult?> getLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getLocation, []),
            returnValue:
                _i2.Future<_i3.HybridLocationResult?>.value(null),
          )
          as _i2.Future<_i3.HybridLocationResult?>);
}
