// Mocks generated by Mockito 5.x from annotations
// in hybrid_location/test/providers/ip_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:hybrid_location/src/utils/geo_api_client.dart' as _i1;
import 'package:mockito/mockito.dart' as _i3;

/// A class which mocks [GeoApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoApiClient extends _i3.Mock implements _i1.GeoApiClient {
  MockGeoApiClient() {
    _i3.throwOnMissingStub(this);
  }

  @override
  _i2.Future<Map<String, dynamic>?> get(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url]),
            returnValue:
                _i2.Future<Map<String, dynamic>?>.value(null),
          )
          as _i2.Future<Map<String, dynamic>?>);

  @override
  _i2.Future<Map<String, dynamic>?> post(
          String? url, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#post, [url, body]),
            returnValue:
                _i2.Future<Map<String, dynamic>?>.value(null),
          )
          as _i2.Future<Map<String, dynamic>?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValueForMissingStub: null,
      );
}
